name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-dev ffmpeg libsdl2-dev \
          libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
          libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libsqlite3-dev \
          sqlite3 libssl-dev libffi-dev libtinfo5 libunwind-dev autoconf libtool \
          pkg-config cmake openjdk-17-jdk

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install "Cython<0.30" buildozer

      - name: Build APK
        run: |
          # কোনো পুরনো ক্যাশ থাকলে ক্লিয়ার করে ফ্রেশ বিল্ড
          rm -rf .buildozer
          yes | buildozer -v android debug
        env:
          ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: messenger-apk
          path: bin/*.apk
