name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.9
          buildozer_cmd: buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: messenger-apk
          path: bin/*.apk
